# Generated by Django 3.0.8 on 2020-10-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainguru', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='static/images/team/', verbose_name='Фото услуги')),
                ('namemain', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
